
/** An event generated by the keyboard driver when a key is pressed. This must
 * come from some higher level device. */
struct KeyboardEvent
{
    Key key;
    bool shiftPressed;
    bool ctrlPressed;
    bool altPressed;
};

